project:
  type: website
  output-dir: docs

website:
  title: "Lena Hicks"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Research.qmd
      - recipes.qmd
      

format:
  html:
    theme: [minty, styles.scss]
    css: styles.css
    mainfont: Merriweather
    toc: true

editor: visual

