---
title: "Recipes"
---

## Plant Based Recipes!

I absolutely love to cook and bake, especially with plant-based foods that are good for my health and the environments health! The challenge of making traditional recipes into plant-based ones offers a lot of frustration, but can also be really exciting! As times gone on, I've moved from following other peoples recipes to making my own, and here's where I share them. My own person recipes list is small for now, but growing day by day! Enjoy!

### The Perfect Chocolate Chip Cookie

Ingredients:

-1/4 cup white sugar

-1 cup brown sugar

-1/2 cup vegan butter (melted)

-1 tsp salt

-1/4 non-dairy milk

-1 tsp vanilla

-1 and 1/2 cups flour

-1/2 tsp baking soda

-3/4 cup chocolate chips (baker's choice)

Directions:

1.  In a large bowl, whisk together the sugar, brown sugar, salt, and butter until combined.

2.  Whisk in non-dairy milk and vanilla, until all sugar has dissolved and the batter is smooth.

3.  Sift in the flour and baking soda, then fold the mixture with a spatula, being careful not to over mix (sometimes I sift half the flour and not the other half if the batter seems runny)

4.  Fold in the chocolate chips evenly.

5.  Chill the dough for at least 30 minutes(but the longer the better, overnight ideal).

6.  Preheat oven to 350°F (180°C).

7.  Scoop the dough with an ice cream scoop onto a parchment paper-lined baking sheet. Be sure to leave at least 2 inches of space between cookies and the edges of the pan so cookies can spread evenly.

8.  Bake for 12-15 minutes, or until cookies just begin to brown.

9.  Cool and enjoy!

### Easy Sheet Pan Dinner

Ingredients

-2 cups brusselsprouts (cut in half)

-1 large sweet potato (cubed)

-1 block extra firm tofu (cubed)

-1 bell pepper (large squares)

-1/2 white onion (large squares)

-1/2 cup brown sugar

-2 tablespoons olive oil

-2 tablespoons vegan butter (melted)

-1 teaspoon red chili powder

-1/2 teaspoon salt

-1/2 teaspoon black pepper

Directions:

1.  Preheat oven to 450 degrees
2.  Line sheet pan with parchment paper
3.  Cut brusselsprouts, sweet potato, tofu, bell pepper, and onion and put into large bowl
4.  In small microwave-safe bowl, melt vegan butter, careful not to burn it
5.  Add the brown sugar, olive oil, chili powder, salt, and pepper to the butter and mix well
6.  Pour glaze into large bowl with the rest of the ingredients and toss well to ensure all is coated
7.  Lay vegetables out onto the sheet pan in a thin layer
8.  Roast in over for 30 minutes, flipping the veggies after 15 minutes
9.  Enjoy warm with grain of your choice!
