---
title: "Research"
---

# Career and Personal Research

Over the past \~5 years, I have been increasingly more involved in the world of research and have dedicated my career to it. I am most strongly invested in the environment and researching ways to mitigate climate change, focusing my academia on such and pursuing jobs in that field. I also enjoy spending my spare time researching other facets of life, like the brain and mental health, food, etc. Here's a place to catalog the research I've done, both big and small, to delve into the exciting creative process that research is.

## FUERTE Fellowship

FUERTE is a Field-based Undergraduate Engagement through Research, Teaching, and Education fellowship that I hold through UCSB. I am of the first cohort for this fellowship, which began in Spring 2022, and encompasses 3 years of research-related work. Last summer I spent time in Mammoth Lakes, California at the Sierra Nevada Aquatic Research Laboratory (SNARL), a UC Reserve with direct affiliates to UCSB, learning from the researchers who work up there and doing my own research on stream ecology.

This summer I am conducting research in the King lab at UCSB under Jennifer King and Jesse Landesman, through my fellowship with FUERTE. We are studying the carbon sequestration of the UCSB restored wetland North Campus Open Space (NCOS) using a basis of measurements taken 5 years ago. We will be in the field shortly beginning our data collection!

A research project I did for my writing class on inner speech, a topic I'm extremely interested in and wanted to explore more of:

## Inner Speech: A Literature Review on the \"Why\'s\"

By Lena Hicks \| Revised 03/08/23\

What is a thought? How do you think? Did you just read the past two lines out loud in your head, can you hear a voice speaking? Maybe yes, maybe no, either way it may come to shock you that people are answering these questions differently than you are. The brain and psychology is a heavily researched field and topic of discussion both in and out of academic settings, but the specific idea of an \"inner voice\" as a subtopic historically is not the most common conversation point. As a whole, the mind component of the brain is especially hard to study, as no one can truly get inside another's mind - brains can be scanned, anecdotes can be told, but what the actual truth is, can\'t be known - inner voice is no exception. The study of inner speech in academic research began gaining traction around the 1930\'s in the psychological field thanks to the Soviet psychologist Lev Vygotsky, who through a focus on child development and cognition, inclusive of speech, found that people don\'t start out with an inner voice but rather they develop it, going from talking to oneself out loud to talking to oneself internally. Only upon the translations of Vygotsky\'s work did further researchers beyond himself really begin to look into the topic of internal speech and conduct significant studies, starting around the 1970\'s and 80\'s, and continuing through to modern day. Everyone wants to know the why and the how - why do we internally talk with ourselves, and how do we do so? With a majority of the research into these questions based on the groundwork set by Vygotsky, that everyone has an inner voice that develops, most have either further looked into such phenomena, or tried to go against him and argue for a different reasoning to how we have inner voices. The critical issue with all these different researchers, including Vygotsky, is the assumption made: everyone has an inner voice. Non-academic discourse has helped expose this assumption, via the general public being able to engage on the topic through platforms like TikTok and discern that there are large populations of both those with and without inner voices. The crowdsourcing done through these new media sources show the achilles heel of these early researchers, that assuming everyone has an inner voice hinders research on what does and doesn\'t give cause to having an inner voice. Newer evidence in the academic field post 2000\'s continues to reveal the incorrect assumption made by previous researchers, looking into alternative ways of thinking with no inner voice. More research is needed in the field with the guiding question of \"why don\'t people have inner voices?\" in order for new researchers to make potential breakthroughs.

Researchers heavily cited in the psychological academic field on the topic of inner voice often fail to recognize that not everyone has one, using work by Vygotsky as a basis and hindering their research and knowledge in the subject. This is not to say that research conducted is uninformed or invaluable, but built upon potential fallacies. Ben Alderson-Day and Charles Fernyhough are examples of such, in which these authors within the Department of Psychology at Durham University hold many published works to their names, much within the study of inner speech, and together created a comprehensive review of much of the literature on inner speech and the possible reasonings to why it occurs. This 2015 review of the research, both theoretical and applied, on inner speech (and closely related to topics) held a purpose of identifying the significance and importance of inner speech, the successes and lackings in methods of approaching research, and clarify where gaps of research in the topic still lie, citing 100+ people in this piece. Through their research, Alderson-Day and Fernyhough suggest a high likelihood that people have misunderstandings of their own experiences in regards to inner speech(amongst many other things), making it highly difficult to study, and clear connections have been found to indicate that inner speech should not be equated loosely with \"thinking\" . This last finding gives the prompt to suggest that alternatives to inner speech exist in how the brain conducts thinking, but Alderson-Day and Fernyhough don\'t make that distinction. While their study is very comprehensive, it lacks real recognition for the role that people with no inner voice could have on the gaps of knowledge they evaluated. Rather, they indicate that those without inner speech is a rare phenomena to be disregarded for their study. 

\"The Rate of Inner Speech\" by Rodney Korba, a researcher with the College of Wooster, is a highly cited study in the field of inner voice, that also holds the assumption that everyone has an inner voice. Although Korba isn\'t the most previously accredited researcher, this study has become one of high value in the field for the large claim that the rate of inner speech is 4000+ words per minute. Further reading into his study, published in 1990, recognizes that this claim doesn\'t have much profoundness, as the sampling group contained only 17 males and 21 females all from the same university campus. He also failed to make any positive correlation between the brain activity measured with the self-reported speech and thought from the participants. Korba identifies this, and actually states that the 4000+ words is an estimate from the data he collected, further stating that more comprehensive research should be conducted, but when cited the claim is often referenced as factual. This study likely gained error through assuming all participants had inner speech, where perhaps the reported annoyance and frustration of failure from participants to recognize their own internal speech stemmed from the participants lacking an inner voice, with Korba not acknowledging that possibility. Had the participants been asked about their potential inner speech, or lack thereof,  discussion on those with and without speech might have begun sooner in time, like that of which follows.

The introduction of non-academic commentary on the topic of inner speech through TikTok highlights lack of an inner voice as roughly as common as having one, discrediting the assumption that everyone has an inner voice except for some rare cases made by researchers like Alderson-Day, Fernyhough, and Korba. In the past few years since the arrival and mainstream of TikTok, where anyone and everyone can share their thoughts with the world, the topic of people having and not having an inner voice had a viral effect. Two main sides are at play: those with an inner voice in disbelief not everyone talks to themselves in their head, and those who without an inner voice in disbelief of people actually having a voice inside their head. Insight of what\'s happening in the mind of those without an inner voice is provided by \@daniashleyy, claiming she \"can\'t see anything in \[her\] mind\'s eye,\" how when asked to imagine something she just sees darkness, indicating she has the condition of aphantasia where she can\'t see or create anything visually inside her head. Up until recently, she had no idea other people weren\'t all the same in processing as her, referencing TV shows with characters having inner monologues as made up.  She indicates having a more unique situation of having both no inner voice nor no inner imagery, contrary to \@cultmaker who\'s video of \"what my brain sounds like without an inner monologue\" provides examples of majoritively visualization with almost complete silence, which the comments on the video add to as well. A highlighted comment comes from \@adrentlearner96, disclosing, \"Language and words aren\'t the same as thinking. Deaf people still think. People with no language still think. I think in raw thoughts.\" This comment connects to the finding by Alderson-Day and Fernyhough on thought not equating to inner voice, but makes the connection that therefore many people don\'t have nor need an inner voice. This discussion overall brings more insight to those with no inner voice, and reasoning as to why people can think without an inner voice. Those with inner voices remain incredibly perplexed by the idea of some people not having inner voices though, such as \@lextalktoomuch asking \"Why are we keeping it a secret that most people don\'t hear \[anything\]?\" and to those with no inner voice \"How do you think? What does thinking mean?\" as they reference that their own thought process is by each thought ruminating in their head verbally. While no official credibility can be given to any of these creators, listening to what people outside the academic field have to add to the subject matter brings new enlightenment to the subject. Not only does this all provide substantial evidence and thoughtfulness to the topic that could be used to inform future studies in the academic field on the topic, but it also provides reasoning why differing opinions/experiences were not established sooner. Each side thought their way of thinking true for all. This reasoning can also support why researchers have always assumed everyone has an inner voice, because they themselves do and thought it must be the truth. 

Recent research, majoritively in the post-2000\'s, supports the anecdotal evidence in exposing the assumptions of everyone having an inner voice to be wrong. Russell Hurlburt has a Ph.D. in clinical psychology with lots of his research conducted and presented through University of Nevada, Las Vegas. Hurlburt's research focuses on the inner experience of people, looking into different aspects and effects. He summarizes his main study in a post on Psychology Today, conducted with fellow researcher Chris Heavey, highlighting the \"pristine experiences\" occurring, which can be identified as inner thoughts, feelings, sensations, seeings, etc. Studying university students, he notably found that only 26% of subjects were inwardly talking to themselves from all the samples, while a large majority of the subjects never talked to themselves inwardly. Coincidentally, other subjects were experiencing inner speech 75% of the time that were randomly asked to record their experience. Hurlburt uses this data to very confidently claim inner speech as \"robust phenomena\" that is extremely unique to each individual on whether they always are talking inwardly, sometimes are, or never are. Hulburts claims in this post are very bold and biased to his own findings, which hold both credibility and questioning. His referenced study used 30 participants, making it difficult to have a definitive claim on the inner workings of the brain and not very reliable, but as a whole his research on the \"pristine experience\" has taken place over 40 years; his findings additionally align more so with the modern anecdotal evidence, like from TikTok, that point to inner voice being far less common than other previous academic research. His research opens a channel to potential reasonings and alternatives as to why people do and don\'t have inner voices, giving more experiences beyond the inner voice and inner imagery, which are typically the only components discussed by others. Continuing more research similar to Hurlburts, looking into all possibilities of the workings of the inner mind, may eventually lead to a definitive conclusion on the why\'s and why nots of inner voice. 

As study on the topic of inner voice continues to expand, researchers need to broaden their background sourcing beyond the research that all leads back to the same person, Vygotsky, in order to avoid bias and assumption in their work. Work done by Alderson-Day & Fernyhough, Korba, etc. all show constraints to their analysis through their personal beliefs of everyone having an inner voice influencing their understanding of all sources reviewed, and their own studies conducted. While they recognized the difficulties in researching inner voice and noted how error clearly occurring makes a basis for their work to be inconclusive, they failed to acknowledge that their assumption of everyone having an inner voice played a role. Discourse amongst the general population via TikTok identifies large groups on both sides of the topic, those with and without inner voices, anecdotally supporting the claim that everyone has an inner voice cannot be assumed. The TikTok discourse additionally yields reasoning to why such assumptions have been made, both in and out of the academic field, from both sides making a point to note that they had no idea that other people thought differently from them. Newer research, like Hurlburt\'s, that did not enter the field of study with the assumption that everyone has an inner voice, granted further confirmation to there being a vast range of those with and without one. He identified alternative phenomenons that can occur in the mind with an inactive inner voice. Future research should recognize the previously made assumptions on inner voice and find the value of asking people about their inner mind\'s experience, in order to make the most informed studies and work towards solving the \"why\'s\". Looking into why all the early researchers in the field assumed people have inner voices, inferring they themselves each have inner voices, and simultaneously what kind of work and fields people without inner voices are in would be an intriguing next step in learning the workings of the inner mind. As with the rest of the brain, it will remain a challenging topic of study, but modern technology and research growing has the potential to uncover the origin of inner voice and its lackings. 

#### References

Alderson-Day, Ben, and Fernyhough, Charles. \"Inner Speech: Development, Cognitive Functions, Phenomenology, and Neurobiology.\" Psychological Bulletin. Vol. 141, Issue 5 (2015): 931-65. https://doi.org/10.1037/bul0000021. 

Danielle (\@daniashleyy). \"#innermonologue #thinking\" Tiktok, October 13, 2022.; (\@cultmaker). \"Can\'t talk right now, doing quiet brain sh\*t #innermonologue\" Tiktok, February 17, 2021. <https://www.tiktok.com/t/ZTRtEWtD7/>, <https://www.tiktok.com/t/ZTRtEGGCJ/>

Hurlburt, Russell T. \"Not everyone conducts inner speech.\" Psychology Today, October 26, 2011. <https://www.psychologytoday.com/us/blog/pristine-inner-experience/201110/not-everyone-conducts-inner-speech>

Korba, Rodney J. \"The Rate of Inner Speech.\" Perceptual and Motor Skills. Vol. 71, Issue 3 (1990): 1043-1052. <https://doi.org/10.2466/pms.1990.71.3.1043>

(\@excerpts.and.stories). \"i would go insane with an internal monologue #internalmonologue #thoughts #innervoice #shutupitisnot\" Tiktok, January 5, 2023. ; (\@lextalktoomuch) \"i have questions!! #lextalktoomuch #innermonologue\" Tiktok, January 15, 2023. <https://www.tiktok.com/t/ZTRtEWkMe/>

Vygotsky, Lev S. Edited and new foreword: Kozulin, Alex. Thought and language. MIT Press, 2012. <https://books.google.com/books?hl=en&lr=&id=rgr-DwAAQBAJ&oi=fnd&pg=PR4&ots=acTdLLHJKk&sig=S8pP9Dif516AGe7Dv9b6OAgUttU#v=onepage&q&f=false>
